# Docker Compose to run app + PostgreSQL
version: "3.8"

services:
    app:
        build: .
        ports:
            - "${APP_PORT:-8000}:8000"
        environment:
            - DB_HOST=db
            - DB_PORT=${DB_PORT:-5432}
            - DB_USER=${DB_USER:-postgres}
            - DB_PASSWORD=${DB_PASSWORD:-postgres}
            - DB_NAME=${DB_NAME:-messaging_db}
            - APP_NAME=${APP_NAME:-Messaging API}
            - DEBUG=${DEBUG:-True}
        depends_on:
            - db
        volumes:
            - .:/app
        networks:
            - app-network

    db:
        image: postgres:15
        container_name: postgres-01
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
            POSTGRES_DB: ${DB_NAME:-messaging_db}
        ports:
            - "${DB_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
