name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: ${{ env.DB_USER || 'postgres' }}
                    POSTGRES_PASSWORD: ${{ env.DB_PASSWORD || 'postgres' }}
                    POSTGRES_DB: ${{ env.DB_NAME || 'messaging_db' }}
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install just
              run: |
                  curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

            - name: Install dependencies
              run: |
                  just install

            - name: Run migrations
              env:
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_USER: postgres
                  DB_PASSWORD: postgres
                  DB_NAME: messaging_db
              run: |
                  just migrate

            - name: Run tests
              env:
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_USER: postgres
                  DB_PASSWORD: postgres
                  DB_NAME: messaging_db
              run: |
                  just test
